name: Build Go Code

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: ""
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Config Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build project
      - name: Build project
        run: go build -v ./...

      # Save build artifact
      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: .
