name: Build Go Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Config Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build project
      - name: Build project
        run: go build -v ./...

      # Run tests
      - name: Run tests
        run: go test -v ./...
