name: Test Go Code

on:
  workflow_run:
    workflows: ["Build Go Code"] # Nome do workflow de build
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ success() }} # Garante que o workflow de teste sรณ seja executado se o de build for bem-sucedido

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: go test -v ./...
